version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  # ses
commands:
  dependencies:
    steps:
      - run:
          name: Installing necessary packages
          command: |
            sudo apt update
            sudo apt install -y tar gzip curl software-properties-common
      - run:
          name: Installing ansible
          command: |
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible  

# Define the jobs we want to run for this project
jobs:

  lint-dockerfile:
      executor: docker/machine
      steps:
        - checkout
        - docker/check
        - docker/hadolint:
            dockerfiles: ./Dockerfile
            executor-class: medium
            # hadolint-tag: 2.2.0-debian
        # - docker/build:
            

      
  create-ec2-instance:
    docker:
      - image: cimg/aws:2023.01
    steps:
      - checkout
      # - dependencies
      - run:
          name: create microk8s ec2 instance
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/minikube-ec2.yml \
              --stack-name "finalProject-${CIRCLE_WORKFLOW_ID:0:7}" \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
              --region us-east-1 \
              --tags project=finalProject

  get-instance-id:
    docker:
      - image: cimg/aws:2023.01
    steps:
      - checkout
      - run:
          name: Add instance IP to ansible inventory
          command: |
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
            cat .circleci/ansible/inventory.txt
        
      - persist_to_workspace:
            root: ~/
            paths:
              - project/.circleci/ansible/inventory.txt

# Orchestrate our job run sequence
workflows:
  default:
    jobs:
      - lint-dockerfile
      # - create-ec2-instance
      # - get-instance-id